### ISSUE TITLE
DictTT musings

### ISSUE THREAD

**Issue by sirpercival** [Zulko/easyAI#11]
Currently there's no native means for saving a DictTT to a file. Might such a one be made to exist?

I'm also curious if there's a way to account for symmetry in game configurations, to reduce the amount of required ttentries in your DictTT.

**Comment by Zulko** [comment]
It would be possible to save a DictTT to a file, with the pickle module. I see your point with game symmetry but I'm not sure it would be trivial to implement. That would be a special DictTT with a "normalize" and "unnormalize" method for both the rrepresentation of a game and the representation of a move. Something like this...

**Comment by JohnAD** [comment]
This is being worked on in issue #27
