### ISSUE TITLE
Can easyAI deal with games where the same player moves repeatedly?

### ISSUE THREAD

**Issue by danielvarga** [Zulko/easyAI#14]
Can easyAI deal with games where the next player stays the same after the move? Even for chess, which is very much turn-based, it might make some sense to implement a promotion as two different moves by the same player. For some games, this seems almost unavoidable: merging the moves by the same player into meta-moves can be pretty awkward.

**Comment by JohnAD** [comment]
Strictly speaking, I suspect that could be made to work. You could certainly make one of the `possible_moves` be "do nothing". It would be the equivalent of skipping a turn.

However, I'm under the impression that is not what you are really asking. You are perhaps asking if multiple actions withing a single move could be broken up into multiple moves to simplify programming. If one carefully followed state (forcing the opponent to not move) I could see how that could be made to work. Keep in mind, that even if that works, you are effectively subtracting levels from the AI. So, a A-B-A sequence of moves is now the functional equivalent of A. And if only *some* combinations are A-B-A but others are simply A, then the depth of the AI search is very... oddly shaped. It would essentially become 'less intelligent' but only when it decides to use complicated moves.

I recommend not doing this personally. I recommend a list-of-lists for the possible move choices. One might have to resort to some recursion for some games, but the result would be much cleaner IMO.

Just my opinion, the developers might have more insight.
