### ISSUE TITLE
I'd like to make another PR: support for judging equal choices

### ISSUE THREAD

**Issue by JohnAD** [Zulko/easyAI#18]
@Zulko 

It is fairly common for a some of the possible moves to have an equal score at the end. I believe the current algorithm simply chooses the first best selection. But often, from a strategic point of view, some moves are better even if they result in the same level of fitness. I'd like to add another _optional_ function to `TwoPlayersGame`:

```python
def judge_best_of_equal_moves(self, equal_move_list):
    # add code that compares the equal_move_list to the this.board and chooses one
    return best_move
```

This is only called if it exists and only at the end of the negamax function.

If you are okay with this, I'll write the code, update version to '0.0.6', update documentation, and generate a pull request. I'd ask that perhaps `pypi` also be updated as it currently sits at '0.0.4'.

Thanks! John

**Off topic**:

In about a month, I'll probably be writing a "stubborn greedy" AI for this library (made up the name myself.) Instead of parsing a full decision tree, the algorithm only follows a single linear path for each possible top move with the assumption that each player only considers the immediate effect of a decision. So, for example, if the immediate list of possible moves always has 4 choices, then a 20 level 'stubborn greedy' algorithm will only consider 4 x 4 x 20 possible decisions. It will almost _always_ return bad results, but for some games it might return interesting results. I suspect it is similar to SSS except both the MAX and MIN only select one path so that the result is a linear algorithm rather than exponential. There might already be a name for this, but I'm not an AI expert.

**Comment by Zulko** [comment]
Hey,

For the first point i am not sure, if some moves are better, then maybe the fitness should reflect that ? I would say you should refine your score to influence the moves. Can you give examples where your method would be necessary ?

For the second point, I'm not completely sure how it will work, so I'd have to see it working :).

**Comment by JohnAD** [comment]
A good example is the one I'm working on: Mancala. For Negamax, the fitness should reflect the goal: winning the game. So, when it look 6 moves ahead, it is strictly looking at the score to determine fitness. Essentially, the final score is the **strategic** goal.

However, sometimes, of the immediate 5 to 20 moves possible in the current turn, two or three might have an equal fitness. When equal, it makes sense to use short term **tactics** instead.

For example, in the Kalah version of Mancala one can 'capture' opposing seeds by stopping in an empty pit. So choosing an otherwise equal move that leaves empty pits near the store puts pressure on the other player to prevent a foolish capture, thus reducing the opponents options.

You wouldn't want to put such thinking into the long-term fitness as it is not relevant to the long game. You can't win with "threatening empty pits". You can only win by having the most seeds.

Of course, if a game is taken to full solution, then tactics are not relevant. But I suspect one would have to wait a week or so between turns on a mega-computer to make that work. Doesn't make for a fun mobile app. :)

I can see two other ways to introduce tactics that are only considered in the short term:

1. You could modify the `scoring` function to pass a `turn_number` of some kind. With that, the fitness scoring can change based on the number of levels deep into the game tree. Then one could write a complex scoring that emphasizes tactics early but emphasizes strategy later. I suspect this would break some proper alpha-beta pruning as the scoring methodology would be based in part on the current depth into the decision tree. In other words, the scores are not strictly reflexive any more.

Also, the scoring function becomes complex to write. I definitely don't want short term tactics to modify the outlook of the algorithm unless the long term fitness's are otherwise the same.

2. Have the AI classes optionally return a list-of-tuples containing fitness/move/board, rather than a single move. One could then use that list to manually consider the best among equals. The big downside is that trick can only be used for the 'get_move()' method of using the library. The '.play()' method can't do that.

And then there is my option:

3. Adding the optional function. I've actually written the code if you would like to see it. It adds about twenty lines of code to the `negamax` function. It would be strictly optional in the same sense that `unmake_move` is optional: optional for both the library user and the AI algorithm itself.

John

**Comment by JohnAD** [comment]
Having slept on it another night, there is a fourth option: make the tactics a strictly minor part of fitness. So, for the Mancala example, multiply the score by 10 for fitness; then add tactical considerations that have a smaller range, such as -3 to +3. That way, they never overwhelm the strategic consideration. Perhaps switch to a floating point fitness score. It will slow things down exponentially as the tactical judgement is a bunch of considerations, but it might work. Would have to try it.

On a personal level, of course, I'm already using my own version of easyAI since 0.0.5 isn't on PyPi yet; and I've already added the function support. This is more about adding a feature to the project.

**Comment by Zulko** [comment]
Yes, your option 4 is the right way to go. Sorry for forgetting to push to Pypi, will do that very soon.
