### ISSUE TITLE
I'm writing a non-recursive version

### ISSUE THREAD

**Issue by JohnAD** [Zulko/easyAI#20]
I wrote a less-recursive version yesterday (recursive but uses less stack space) and got a 400% performance improvement. Inspired, I've started writing a fully non-recursive stack-free version. Essentially, it uses a pre-allocated list of state dictionaries in an iterative manner.

The basic algorithm is now working; I just need to add the alpha/beta pruning next.

I'm thinking this might be of value to the repo and may put it in a PR. Which of the following do you all suggest?:

* Keeping the same `Negamax` class adding a parameter such as `non-recurse=True` to invoke the non-recursive function. Or,
* Adding a new class, such as `NegamaxNR` that uses the non-recursive version.
* Something else...

BTW, there are two caveats for the non-recursive version: 

1. in addition to needing `ttentry()` it must also have a `ttrecover()`. The `ttrecover()` takes the immutable key (created by `ttentry()`) recovers the game board. If the game is too complex for such a recovery to work, then the recursive version will need to be used.

2. The game must be *functional* in the sense that it must always be repeatable. If the game involves any use of `random` or an element of input from the outside world, then it will probably break. Use the recursive version.

And also, `unmake_move` is ignored. Not really sure how to support that in the non-recursive version.

The first version will also ignore the TT table; but it could certainly be added in. For some games, that would speed things up even further.

**Comment by JohnAD** [comment]
(side note: my "Stubborn Greedy" AI is about done also. That would be a separate PR.)

**Comment by JohnAD** [comment]
Done. I think. this is really hard to test.

The fully iterative non-recursive gives another 50% speed improvement. (At least for the Kalah variant of Mancala.)

I'll get a PR request put together in the next few days. If okay, I'll also write a test suite. That way, any future changes to code can be run against known correct results.

**Comment by Zulko** [comment]
Sounds great thanks ! I am for option 2, a new AI class called ``NonRecursiveNegamax``. It deserves its own class because the use conditions will be a bit different.

**Comment by JohnAD** [comment]
PR #21
