### ISSUE TITLE
Difficult to find this repo on GitHub: suggest adding topics

### ISSUE THREAD

**Issue by JohnAD** [Zulko/easyAI#33]
I'd do it myself, but apparently GitHub restricts the `Add topics` function (under the repo description) to the owner.

I recommend adding:

`minimax`
`negamax`
`ai`
`game-development`
`two-player`
`non-recursive`
`sss-algorithm`
`dual-algorithm`

This should make it easier for folks wanting to find something like *easyAI* on GitHub.

**Comment by Zulko** [comment]
Thanks for the suggestion it's done !
