### ISSUE TITLE
documentation clarification on "scoring"

### ISSUE THREAD

**Issue by aisaksen** [Zulko/easyAI#8]
The documentation is not currently clear on how to do "scoring" from the perspective of each player for games with points.   For example, lets say each player goes around a game picking up points (either scoring 1 for player A or -1 for player B, where player A wants to maximize, and player B wants to minimize).   Should scoring return the score from the perspective of game.nplayer?  That is, if game.nplayer==2 then i want to return "-totalscore" instead of returning "totalscore"

I think that scoring is always from the perspective of game.nplayer but I just wanted to confirm before updating the documentation.

(Great job on this library...very useful!)

**Comment by Zulko** [comment]
Thanks for the report. Yes it is from the perpective of the current player. And ok for an update.
